image: cincproject/omnibus-debian
stages:
 - patch
 - package
 - test
 - deploy
 - publish
 - cleanup

variables:
  ORIGIN: https://github.com/inspec/inspec.git
  REF: master
  CHANNEL: unstable

patch:
  stage: patch
  tags:
    - osuosl
  script:
    - echo "Cloning from $ORIGIN"
    - sh patch.sh
    - mkdir -p ${CI_PROJECT_DIR}/{cache,cache/git_cache}
    - echo "cache_dir '${CI_PROJECT_DIR}/cache'" >> inspec/omnibus/omnibus.rb
    - echo "git_cache_dir '${CI_PROJECT_DIR}/cache/git_cache'" >> inspec/omnibus/omnibus.rb
    - sed -i -e 's/^use_git_caching false/use_git_caching true/g' inspec/omnibus/omnibus.rb
  artifacts:
    expire_in: 1d
    paths:
      - inspec/

.package:
  stage: package
  tags:
    - osuosl
  dependencies:
    - patch
  script:
    - source /home/omnibus/load-omnibus-toolchain.sh
    - cd inspec/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - bundle exec omnibus build cinc-auditor --override append_timestamp:false
    - mkdir ${CI_PROJECT_DIR}/data
    - mv -v pkg/cinc-auditor* ${CI_PROJECT_DIR}/data/
    - cp ../VERSION ${CI_PROJECT_DIR}/
  cache:
    paths:
      - cache/*
      - bundle/vendor/*
  artifacts:
    expire_in: 1mo
    paths:
      - data/*
      - VERSION

package:debian-8:
  extends: .package
  image: cincproject/omnibus-debian:8
  cache:
    key: debian:8
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/8
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/8/

package:debian-9:
  extends: .package
  image: cincproject/omnibus-debian:9
  cache:
    key: debian:9
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/9
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/9/

package:debian-10:
  extends: .package
  image: cincproject/omnibus-debian:10
  cache:
    key: debian:10
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/10
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/10/

package:ubuntu-16.04:
  extends: .package
  image: cincproject/omnibus-ubuntu:16.04
  cache:
    key: ubuntu:16.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/16.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/16.04/

package:ubuntu-18.04:
  extends: .package
  image: cincproject/omnibus-ubuntu:18.04
  cache:
    key: ubuntu:18.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/18.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/18.04/

package:centos-6:
  extends: .package
  image: cincproject/omnibus-centos:6
  cache:
    key: centos:6
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/6
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/el/6/

package:centos-7:
  extends: .package
  image: cincproject/omnibus-centos:7
  cache:
    key: centos:7
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/7
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/el/7/

package:centos-8:
  extends: .package
  image: cincproject/omnibus-centos:8
  cache:
    key: centos:8
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/8
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/el/8/

package:opensuse-15:
  extends: .package
  image: cincproject/omnibus-opensuse:15
  cache:
    key: opensuse:15
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/sles/15
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/sles/15/

package:macos-10.14:
  extends: .package
  tags:
    - macos-10.14
  script:
    - source /Users/omnibus/load-omnibus-toolchain.sh
    - cd inspec/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - sudo rm -rf /var/cache/omnibus/pkg/*
    - sudo bundle exec omnibus build cinc-auditor --override append_timestamp:false
    - mkdir -p ${CI_PROJECT_DIR}/data/mac_os_x/10.14
    - sudo chown -R omnibus:omnibus pkg
    - mv -v pkg/cinc*dmg* ${CI_PROJECT_DIR}/data/mac_os_x/10.14/
    - sudo bundle exec omnibus clean cinc-auditor
    - sudo rm -rf /opt/cinc-auditor/*
  cache:
    key: macos:10.14

package:macos-10.15:
  extends: .package
  tags:
    - macos-10.15
  script:
    - source /Users/omnibus/load-omnibus-toolchain.sh
    - cd inspec/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - sudo rm -rf /var/cache/omnibus/pkg/*
    - /usr/local/bin/gsed -i "s:^cache_dir.*:cache_dir '/var/cache/omnibus/cache':" omnibus.rb
    - /usr/local/bin/gsed -i "s:^git_cache_dir.*:git_cache_dir '/var/cache/omnibus/git_cache':" omnibus.rb
    - sudo bundle exec omnibus build cinc-auditor --override append_timestamp:false
    - mkdir -p ${CI_PROJECT_DIR}/data/mac_os_x/10.15
    - sudo chown -R omnibus:omnibus pkg
    - mv -v pkg/cinc*dmg* ${CI_PROJECT_DIR}/data/mac_os_x/10.15/
    - sudo bundle exec omnibus clean cinc-auditor
    - sudo rm -rf /opt/cinc-auditor/*
  cache:
    key: macos:10.15

package:windows-2012r2:
  extends: .package
  tags:
    - windows-x64
  script:
    - $ErrorActionPreference = "Stop"
    - C:\omnibus\load-omnibus-toolchain.ps1
    - cd inspec\omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - bundle exec omnibus build cinc-auditor --override append_timestamp:false
    - mkdir.exe -p ${CI_PROJECT_DIR}/data/windows/2012r2
    - mv.exe -v pkg/cinc-auditor* ${CI_PROJECT_DIR}/data/windows/2012r2
    - bundle exec omnibus clean cinc-auditor
  cache:
    key: windows:2012r2

.test:
  stage: test
  tags:
    - osuosl
  script:
    - cinc-auditor version
    - cinc-auditor detect
    - cinc-auditor exec test-baseline

.test-windows:
  tags:
    - windows-x64
  before_script:
    - ./scripts/install-cinc-auditor.ps1
  script:
    - $ErrorActionPreference = "Stop"
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - echo $env:PATH
    - cinc-auditor version
    - cinc-auditor detect
    - cinc-auditor exec test-baseline
  after_script:
    - ./scripts/uninstall-cinc-auditor.ps1

test:debian-8:
  extends: .test
  image: cincproject/omnibus-debian:8
  dependencies:
    - package:debian-8
  before_script:
    - dpkg -i data/debian/8/cinc-auditor*.deb

test:debian-9:
  extends: .test
  image: cincproject/omnibus-debian:9
  dependencies:
    - package:debian-9
  before_script:
    - dpkg -i data/debian/9/cinc-auditor*.deb

test:debian-10:
  extends: .test
  image: cincproject/omnibus-debian:10
  dependencies:
    - package:debian-10
  before_script:
    - dpkg -i data/debian/10/cinc-auditor*.deb

test:ubuntu-16.04:
  extends: .test
  image: cincproject/omnibus-ubuntu:16.04
  dependencies:
    - package:ubuntu-16.04
  before_script:
    - dpkg -i data/ubuntu/16.04/cinc-auditor*.deb

test:ubuntu-18.04:
  extends: .test
  image: cincproject/omnibus-ubuntu:18.04
  dependencies:
    - package:ubuntu-18.04
  before_script:
    - dpkg -i data/ubuntu/18.04/cinc-auditor*.deb

test:centos-6:
  extends: .test
  image: cincproject/omnibus-centos:6
  dependencies:
    - package:centos-6
  before_script:
    - yum -y install data/el/6/cinc-auditor*.rpm

test:centos-7:
  extends: .test
  image: cincproject/omnibus-centos:7
  dependencies:
    - package:centos-7
  before_script:
    - yum -y install data/el/7/cinc-auditor*.rpm

test:centos-8:
  extends: .test
  image: cincproject/omnibus-centos:8
  dependencies:
    - package:centos-8
  before_script:
    - yum -y install data/el/8/cinc-auditor*.rpm

test:opensuse-15:
  extends: .test
  image: cincproject/omnibus-opensuse:15
  dependencies:
    - package:opensuse-15
  before_script:
    - zypper in -y data/sles/15/cinc-auditor*.rpm

test:macos-10.14:
  extends: .test
  tags:
    - macos-10.14
  dependencies:
    - package:macos-10.14
  script:
    - sudo scripts/install-cinc-auditor-macos.sh
    - cinc-auditor version
    - cinc-auditor detect
    - cinc-auditor exec test-baseline
    - sudo scripts/uninstall-cinc-auditor-macos.sh

test:macos-10.15:
  extends: .test
  tags:
    - macos-10.15
  dependencies:
    - package:macos-10.15
  script:
    - sudo scripts/install-cinc-auditor-macos.sh
    - cinc-auditor version
    - cinc-auditor detect
    - cinc-auditor exec test-baseline
    - sudo scripts/uninstall-cinc-auditor-macos.sh

test:windows-2012r2:
  extends: .test-windows
  dependencies:
    - package:windows-2012r2

.ssh-setup:
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy to packagecloud:
  stage: deploy
  allow_failure: true
  only:
    - master
  tags:
    - downloads
  script:
    - bundle install
    - sh deploy.sh

deploy:
  when: manual
  stage: deploy
  extends: .ssh-setup
  tags:
    - osuosl
  dependencies:
    - package:debian-8
    - package:debian-9
    - package:debian-10
    - package:ubuntu-16.04
    - package:ubuntu-18.04
    - package:centos-6
    - package:centos-7
    - package:centos-8
    - package:opensuse-15
    - package:macos-10.14
    - package:macos-10.15
    - package:windows-2012r2
  script:
    - ssh cinc@${DOWNLOADS_HOST} "mkdir -p /data/incoming/files/${CHANNEL}/cinc-auditor/$(cat VERSION)/"
    - rsync -avH --delete data/ cinc@${DOWNLOADS_HOST}:/data/incoming/files/${CHANNEL}/cinc-auditor/$(cat VERSION)/
    - ssh cinc@${DOWNLOADS_HOST} "chmod 755 /data/incoming/files/${CHANNEL}/cinc-auditor/$(cat VERSION)/"

publish:
  when: manual
  stage: publish
  extends: .ssh-setup
  dependencies: []
  tags:
    - downloads
  script:
    - sudo mkdir -p /data/mirror/files/${CHANNEL}/cinc-auditor
    - sudo /usr/bin/rsync -avH /data/incoming/files/${CHANNEL}/cinc-auditor/ /data/mirror/files/${CHANNEL}/cinc-auditor/
    - ssh -q cinc@${MIRROR_HOST} "~/sync-from-master"

.cleanup:
  stage: cleanup
  dependencies: []
  variables:
    GIT_CHECKOUT: "false"
  when: always
  script:
    - sudo rm -rf inspec/

cleanup:macos-10.14:
  extends: .cleanup
  tags:
    - macos-10.14

cleanup:macos-10.15:
  extends: .cleanup
  tags:
    - macos-10.15
