image: cincproject/omnibus-debian
stages:
 - patch
 - package
 - test
 - deploy
 - publish

variables:
  GIT_SUBMODULE_STRATEGY: normal
  CHANNEL: unstable

patch:
  stage: patch
  tags:
    - osuosl
  script:
    - sh patch.sh
  artifacts:
    expire_in: 1d
    paths:
      - inspec/

.package:
  stage: package
  tags:
    - osuosl
  dependencies:
    - patch
  script:
    - source /home/omnibus/load-omnibus-toolchain.sh
    - cd inspec/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - bundle exec omnibus build cinc-auditor --override append_timestamp:false
    - mkdir ${CI_PROJECT_DIR}/data
    - mv -v pkg/cinc-auditor* ${CI_PROJECT_DIR}/data/
  cache:
    paths:
      - cache/*
      - bundle/vendor/*
  artifacts:
    expire_in: 1mo
    paths:
      - data/*

package:debian-8:
  extends: .package
  image: cincproject/omnibus-debian:8
  cache:
    key: debian:8
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/8
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/8/

package:debian-9:
  extends: .package
  image: cincproject/omnibus-debian:9
  cache:
    key: debian:9
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/9
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/9/

package:ubuntu-16.04:
  extends: .package
  image: cincproject/omnibus-ubuntu:16.04
  cache:
    key: ubuntu:16.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/16.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/16.04/

package:ubuntu-18.04:
  extends: .package
  image: cincproject/omnibus-ubuntu:18.04
  cache:
    key: ubuntu:18.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/18.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/18.04/

package:centos-6:
  extends: .package
  image: cincproject/omnibus-centos:6
  cache:
    key: centos:6
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/centos/6
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/centos/6/

package:centos-7:
  extends: .package
  image: cincproject/omnibus-centos:7
  cache:
    key: centos:7
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/centos/7
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/centos/7/

.test:
  stage: test
  tags:
    - osuosl
  script:
    - cinc-auditor exec test-baseline

test:debian-8:
  extends: .test
  image: cincproject/omnibus-debian:8
  dependencies:
    - package:debian-8
  before_script:
    - dpkg -i data/debian/8/cinc-auditor*.deb

test:debian-9:
  extends: .test
  image: cincproject/omnibus-debian:9
  dependencies:
    - package:debian-9
  before_script:
    - dpkg -i data/debian/9/cinc-auditor*.deb

test:ubuntu-16.04:
  extends: .test
  image: cincproject/omnibus-ubuntu:16.04
  dependencies:
    - package:ubuntu-16.04
  before_script:
    - dpkg -i data/ubuntu/16.04/cinc-auditor*.deb

test:ubuntu-18.04:
  extends: .test
  image: cincproject/omnibus-ubuntu:18.04
  dependencies:
    - package:ubuntu-18.04
  before_script:
    - dpkg -i data/ubuntu/18.04/cinc-auditor*.deb

test:centos-6:
  extends: .test
  image: cincproject/omnibus-centos:6
  dependencies:
    - package:centos-6
  before_script:
    - yum -y install data/centos/6/cinc-auditor*.rpm

test:centos-7:
  extends: .test
  image: cincproject/omnibus-centos:7
  dependencies:
    - package:centos-7
  before_script:
    - yum -y install data/centos/7/cinc-auditor*.rpm

.ssh-setup:
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy to packagecloud:
  stage: deploy
  allow_failure: true
  only:
    - master
  tags:
    - downloads
  script:
    - bundle install
    - sh deploy.sh

deploy:
  when: manual
  stage: deploy
  extends: .ssh-setup
  tags:
    - osuosl
  dependencies:
    - package:debian-8
    - package:debian-9
    - package:ubuntu-16.04
    - package:ubuntu-18.04
    - package:centos-6
    - package:centos-7
  script:
    - ssh cinc@${DOWNLOADS_HOST} "mkdir -p /data/incoming/files/${CHANNEL}/cinc-auditor"
    - rsync -avH --delete data/ cinc@${DOWNLOADS_HOST}:/data/incoming/files/${CHANNEL}/cinc-auditor/
    - ssh cinc@${DOWNLOADS_HOST} "chmod 755 /data/incoming/files/${CHANNEL}/cinc-auditor"

publish:
  when: manual
  stage: publish
  extends: .ssh-setup
  dependencies: []
  tags:
    - downloads
  script:
    - sudo mkdir -p /data/mirror/files/${CHANNEL}/cinc-auditor
    - sudo /usr/bin/rsync -avH /data/incoming/files/${CHANNEL}/cinc-auditor /data/mirror/files/${CHANNEL}/cinc-auditor
    - ssh -q cinc@${MIRROR_HOST} "~/sync-from-master"
