.package:
  stage: package
  tags:
    - docker-x86_64
  dependencies:
    - patch
  script:
    - bash build.sh
    - cd inspec/omnibus
    - mkdir ${CI_PROJECT_DIR}/data
    - mv -v pkg/cinc-auditor* ${CI_PROJECT_DIR}/data/
    - cp ../VERSION ${CI_PROJECT_DIR}/
  cache:
    paths:
      - cache/*
      - bundle/vendor/*
    when: always
  artifacts:
    expire_in: 1mo
    paths:
      - data/*
      - VERSION

.package:amazonlinux:
  extends: .package
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/amazon/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,json} ${CI_PROJECT_DIR}/data/amazon/${PLATFORM_VER}/

.package:centos:
  extends: .package
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,json} ${CI_PROJECT_DIR}/data/el/${PLATFORM_VER}/

.package:debian:
  extends: .package
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/*.{deb,json} ${CI_PROJECT_DIR}/data/debian/${PLATFORM_VER}/

.package:macos:
  extends: .package
  script:
    - bash build-macos.sh
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/mac_os_x/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/cinc*dmg* ${CI_PROJECT_DIR}/data/mac_os_x/${PLATFORM_VER}/
    - sudo chown -R omnibus:omnibus cache/ bundle/
    - sudo rm -rf /opt/cinc-auditor/
  variables:
    OMNIBUS_FIPS_MODE: "false"

.package:opensuse:
  extends: .package
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/sles/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,json} ${CI_PROJECT_DIR}/data/sles/${PLATFORM_VER}/

.package:rockylinux:
  extends: .package
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/rocky/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,json} ${CI_PROJECT_DIR}/data/rocky/${PLATFORM_VER}/

.package:ubuntu:
  extends: .package
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/${PLATFORM_VER}
    - mv -v ${CI_PROJECT_DIR}/data/*.{deb,json} ${CI_PROJECT_DIR}/data/ubuntu/${PLATFORM_VER}/

.package:windows:
  extends: .package
  script:
    - $ErrorActionPreference = "Stop"
    - C:\omnibus\load-omnibus-toolchain.ps1
    - bash build-windows.sh
  after_script:
    - $ErrorActionPreference = "Stop"
    - mkdir.exe -p ${CI_PROJECT_DIR}/data/windows/${PLATFORM_VER}
    - mv.exe -v ${CI_PROJECT_DIR}/data/cinc* ${CI_PROJECT_DIR}/data/windows/${PLATFORM_VER}
    - Remove-Item -Recurse -Force C:\cinc-project
